import { FaSearch } from "react-icons/fa";
import { TbClipboardList } from "react-icons/tb";
import "@/styles/navbar.css";
import "@/styles/global.css";
import Hero from "@/comp/hero";
import MainBody from "@/comp/mainBody";
import "@/styles/mainPageQuery.css";
export const metadata = {
  title: "WellShop",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
